version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.65.0
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: Run Tests
          command: "cd metadata && cargo test --tests"
